# Generated by Django 5.2.6 on 2025-09-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='StudyPlan',
            new_name='studyplan',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='Subject_priority',
            new_name='subject_priority',
        ),
    ]
