# Generated by Django 5.2.6 on 2025-09-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_rename_studyplan_subject_studyplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='allocated_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='in progress'),
        ),
    ]
